In [2]:
import numpy as np

## Tensor(similar to arrays)

### 0-D tensor/Scalar

In [22]:
x0=np.array(5)
print("x0:",x0)
print("Dimensions of x0:",x0.ndim)
print("Shape of x0:",x0.shape)
print("Size of x0:",x0.size)
print("Datatype of x0:",x0.dtype)

x0: 5
Dimensions of x0: 0
Shape of x0: ()
Size of x0: 1
Datatype of x0: int64


### 1-D tensor/Vector

In [23]:
x1=np.array([5,6,7])
print("x1:",x1)
print("Dimensions of x1:",x1.ndim)
print("Shape of x1:",x1.shape)
print("Size of x1:",x1.size)
print("Datatype of x1:",x1.dtype)

x1: [5 6 7]
Dimensions of x1: 1
Shape of x1: (3,)
Size of x1: 3
Datatype of x1: int64


### 2-D tensor/Matrix

In [28]:
x2=np.array([[2,4,5],[6,7,8]])
print("x2:",x2)
print("Dimensions of x2:",x2.ndim)
print("Shape of x2:",x2.shape)
print("Size of x2:",x2.size)
print("Datatype of x2:",x2.dtype)

x2: [[2 4 5]
 [6 7 8]]
Dimensions of x2: 2
Shape of x2: (2, 3)
Size of x2: 6
Datatype of x2: int64


### 3-D tensor

In [39]:
x3=np.array([[[4,5],[6,7]],[[8,9],[10.2,14.5]]])
print("x3:",x3)
print("Dimensions of x3:",x3.ndim)
print("Shape of x3:",x3.shape)
print("Size of x3:",x3.size)

print("Datatype of x3:",x3.dtype)

x3: [[[ 4.   5. ]
  [ 6.   7. ]]

 [[ 8.   9. ]
  [10.2 14.5]]]
Dimensions of x3: 3
Shape of x3: (2, 2, 2)
Size of x3: 8
Datatype of x3: float64


## Some functions

In [41]:
print("np.zeros of shape(2.2):",np.zeros((2,2)))
print("np.ones of shape(2.2):",np.ones((2,2)))
print("identity matrix of shape(2.2):\n",np.eye((5)))    #rows=columns in identity matrix

np.zeros of shape(2.2): [[0. 0.]
 [0. 0.]]
np.ones of shape(2.2): [[1. 1.]
 [1. 1.]]
identity matrix of shape(2.2):
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Indexing in tensors

In [53]:
x=np.array([1,2,3,4,5])
y=np.array([[23.2,45,7.4],[0.4,23.9,9]])
print(f"Element [0] in X:{x[0]} and element [4] in X:{x[4]}")
print(f"Element row=1st and column=3([0][2]) in Y:{y[0][2]} and element [1][0] in X:{y[1][0]}")

Element [0] in X:1 and element [4] in X:5
Element row=1st and column=3([0][2]) in Y:7.4 and element [1][0] in X:0.4


### Integer array indexing(storing array/tensor in variable)

In [71]:
matrix_3_2=np.array([[2,4,5],[9.4,3.5,7.1]])
print(f"matrix/2-D tensor of order 3*2:\n{matrix_3_2}\n type:{type(matrix_3_2)}")
row=np.array([2,4,7])
print(f"vector/1-D tensor of order 3*2:\n{row}\n type:{type(row)}")

matrix/2-D tensor of order 3*2:
[[2.  4.  5. ]
 [9.4 3.5 7.1]]
 type:<class 'numpy.ndarray'>
vector/1-D tensor of order 3*2:
[2 4 7]
 type:<class 'numpy.ndarray'>


### Slicing

In [95]:
#array[row_start:row_end:row_step, col_start:col_end:column_step]
m=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]]) 
print(m)
print(f"1st row:\n{m[0:1]}")
print(f"2st row:\n{m[1:2]}")

print(f"1st column:\n{m[:,0:1]}")
print(f"2nd column:\n{m[0:3,1:2]}")

print(f"Taking 2 rows and 2 columns:{m[]}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1st row:
[[1 2 3]]
2st row:
[[4 5 6]]
1st column:
[[1]
 [4]
 [7]]
2nd column:
[[2]
 [5]
 [8]]
